version: "3.8"
services:
    jekyll:
        image: jekyll/jekyll:3.8
        container_name: website
        command: jekyll serve --force_polling
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
